# Private repo are located on Gitlab CI
# This script exist here for archive and starter
image: "node:12-alpine"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    - node_modules/

stages:
  - build
  - test
  - deploy
  
staging_build:
  stage: build
  only: 
    - staging
    - ci-feature
  before_script:
    - source .env
    - cd $THEME_NAME
    - npm install
  script:
    - echo "Here we are on build step"
    - npm run build
    - echo $PROJECT_NAME
    - echo $THEME_NAME
  artifacts:
    paths:
      - ./wpdevstack/dist/


staging_deploy:
  stage: deploy
  only: 
    - staging
    - ci-feature
  before_script:
    - source .env
    - apk --no-cache add lftp
    - cd $THEME_NAME
  script:
    - echo "Here we are on Deploy step"
    - lftp --version
    - ls

production_build:
  stage: build
  only:
    - production
  script:
    - echo "Here we are on build step"

production_deploy:
  stage: deploy
  only: 
    - production
  script:
    - echo "Here we are on build step"
