# Private repo are located on Gitlab CI
# This script exist here for archive and starter
image: "node:12-alpine"
variables:
  REMOTE_DESTINATION_DIR: ./wp/wp-content/themes
  CI_SYNC_TYPE: RSYNC
  STAGE_URL: https://wpdevstack.ecrannoir.be

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    - node_modules/

stages:
  - build
  - test
  - deploy
  
# staging_build:
#   stage: build
#   only: 
#     - staging
#     - ci-feature
#   before_script:
#     - source .env
#     - cd $THEME_NAME
#     - npm install
#   script:
#     - echo "Here we are on build step"
#     - npm run build
#     - echo $PROJECT_NAME
#     - echo $THEME_NAME
#   artifacts:
#     paths:
#       - ./wpdevstack/dist/
#   environment:
#     name: stage
#     url: $STAGE_URL


# staging_ftp_deploy:
#   stage: deploy
#   only: 
#     refs:
#       - staging
#       - ci-feature
#     variables:
#       - $CI_SYNC_TYPE == "FTP"
#   before_script:
#     - source .env
#     - apk --no-cache add lftp
#   script:
#     - echo "Here we are on Deploy step by ftp"
#     - lftp --version
#     - lftp -e "open $FTP_ADDRESS; user $FTP_LOGIN $FTP_PASSWORD; mirror -X package-lock.json --reverse --verbose --delete $THEME_NAME $REMOTE_DESTINATION_DIR/; bye"
#   environment:
#     name: stage
#     url: $STAGE_URL
  
staging_rsync_deploy:
  stage: deploy
  only:
    refs:
      - staging
      - ci-feature
    variables:
      - $CI_SYNC_TYPE == "RSYNC"
  before_script:
    - source .env
    - apk --no-cache add rsync
  script:
    - echo "Here we are on Deploy step by ftp"
  environment:
    name: stage
    url: $STAGE_URL
