# Private repo are located on Gitlab CI
# This script exist here for archive and starter
image: "node:12-alpine"

before_script:
  - apk --no-cache add lftp
  - source .env
  - echo $THEME_NAME

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    - node_modules/

stages:
  - build
  - test
  - deploy
  
staging_build:
  stage: build
  only: 
    - staging
    - ci-feature
  script:
    - echo "Here we are on build step"
    - echo $PROJECT_NAME
    - echo $THEME_NAME
    - lftp --version

staging_deploy:
  stage: deploy
  only: 
    - staging
    - ci-feature
  script:
    - echo "Here we are on build step"

production_build:
  stage: build
  only:
    - production
  script:
    - echo "Here we are on build step"

production_deploy:
  stage: deploy
  only: 
    - production
  script:
    - echo "Here we are on build step"
