# Private repo are located on Gitlab CI
# This script exist here for archive and starter
image: misterio92/ci-php-node:2.0
variables:
  STAGING_REMOTE_DESTINATION_DIR: ./www/wp-content
  PRODUCTION_REMOTE_DESTINATION_DIR: ./www/wp-content
  STAGE_URL: https://wpdevstack.ecrannoir.be
  PRODUCTION_URL: https://wpdevstack.ecrannoir.be
  THEME_DIR: wpdevstack

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm/
    - node_modules/

stages:
  - build
  - test
  - deploy
  
build_job:
  stage: build
  only: 
    # - master
    - staging
    - production
  before_script:
    - source .env
    - apt-get update
    - apt-get install zip unzip -y
    - cd $THEME_NAME
    # - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    # - php composer-setup.php
    # - php -r "unlink('composer-setup.php');"
    # - php composer.phar install
    - npm install
  script:
    - echo "Here we are on build step"
    - npm run production
    - echo $PROJECT_NAME
    - echo $THEME_NAME
  artifacts:
    paths:
      - ./$THEME_DIR/assets/
      - ./$THEME_DIR/languages/
      - ./$THEME_DIR/vendor/
  environment:
    name: stage
    url: $STAGE_URL


ftp_deploy:
  stage: deploy
  only: 
    refs:
      - staging
      # - master 
    variables:
      - $CI_SYNC_TYPE == "FTP"
  before_script:
    - source .env
    - apt-get update
    - apt-get install lftp
  script:
    - echo "Here we are on Deploy step by ftp"
    - rm -rf $THEME_NAME/src/ $THEME_NAME/package.json $THEME_NAME/package-lock.json $THEME_NAME/webpack.config.js $THEME_NAME/.stylelintrc.json
    - lftp --version
    - lftp -e "open $FTP_ADDRESS; user $FTP_LOGIN $FTP_PASSWORD; mirror --reverse --verbose --delete $THEME_NAME $STAGING_REMOTE_DESTINATION_DIR/themes; bye"
    - lftp -e "open $FTP_ADDRESS; user $FTP_LOGIN $FTP_PASSWORD; mirror --reverse --verbose --delete wp/wp-content/plugins/ $STAGING_REMOTE_DESTINATION_DIR/plugins; bye"
  environment:
    name: stage
    url: $STAGE_URL
  
staging_rsync_deploy:
  stage: deploy
  only:
    refs:
      - staging
      # - master 
  before_script:
    - source .env
    - 'which ssh-agent || ( apk --no-cache add rsync openssh-client )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - echo "Here we are on Deploy step by rsync"
    - rm -rf $THEME_NAME/src/ $THEME_NAME/package.json $THEME_NAME/package-lock.json $THEME_NAME/webpack.config.js $THEME_NAME/.stylelintrc.json
    - echo "$STAGING_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh -p22 $STAGING_SSH_USER@$STAGING_SSH_HOST "ls -al"
    - rsync -azPqv --delete $THEME_NAME $STAGING_SSH_USER@$STAGING_SSH_HOST:$STAGING_REMOTE_DESTINATION_DIR/themes
    - rsync -azPqv wp/wp-content/plugins/ $STAGING_SSH_USER@$STAGING_SSH_HOST:$STAGING_REMOTE_DESTINATION_DIR/plugins
  environment:
    name: stage
    url: $STAGE_URL

production_rsync_deploy:
  stage: deploy
  only:
    refs:
      - production
      # - master 
  before_script:
    - source .env
    - 'which ssh-agent || ( apk --no-cache add rsync openssh-client )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - echo "Here we are on Deploy step by rsync"
    - rm -rf $THEME_NAME/src/ $THEME_NAME/package.json $THEME_NAME/package-lock.json $THEME_NAME/webpack.config.js $THEME_NAME/.stylelintrc.json
    - echo "$PRODUCTION_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - ssh -p22 $PRODUCTION_SSH_USER@$PRODUCTION_SSH_HOST "ls -al"
    - rsync -azPqv --delete $THEME_NAME $PRODUCTION_SSH_USER@$PRODUCTION_SSH_HOST:$PRODUCTION_REMOTE_DESTINATION_DIR/themes
    - rsync -azPqv wp/wp-content/plugins/ $PRODUCTION_SSH_USER@$PRODUCTION_SSH_HOST:$PRODUCTION_REMOTE_DESTINATION_DIR/plugins
  environment:
    name: production
    url: $PRODUCTION_URL
