version: '3.1'

services:
  wp:
    image: noveni/wordpress:6.1-php7.4-apache-dev
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: "local_wp_${PROJECT_NAME}"
      WORDPRESS_DEBUG: "true"
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9000
    volumes:
      - ./wp-core:/var/www/html
      - ./${THEME_NAME}:/var/www/html/wp-content/themes/${THEME_NAME}
      - ./${THEME_NAME}-child:/var/www/html/wp-content/themes/${THEME_NAME}-child
      - ./uploads:/var/www/html/wp-content/uploads
      - ./plugins:/var/www/html/wp-content/plugins
    extra_hosts:
      - "${URL}:127.0.0.1"
      - "www.${URL}:127.0.0.1"
    labels:
      - traefik.enable=true
      - traefik.docker.network=local_traefik_webgateway
      - traefik.http.routers.${PROJECT_NAME}.rule=Host(`www.${URL}`)
      - traefik.http.routers.${PROJECT_NAME}.entrypoints=web
      - traefik.http.routers.${PROJECT_NAME}-secure.rule=Host(`www.${URL}`)
      - traefik.http.routers.${PROJECT_NAME}-secure.entrypoints=websecure
      - traefik.http.routers.${PROJECT_NAME}-secure.tls=true
    networks:
      - web
      - default

  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: "local_wp_${PROJECT_NAME}"
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./.db:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    image: noveni/phpmyadmin
    restart: always
    environment:
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    labels:
      - traefik.enable=true
      - traefik.docker.network=local_traefik_webgateway
      - traefik.http.routers.${PROJECT_NAME}-phpmyadmin-secure.rule=Host(`phpmyadmin.${URL}`)
      - traefik.http.routers.${PROJECT_NAME}-phpmyadmin-secure.entrypoints=websecure
      - traefik.http.routers.${PROJECT_NAME}-phpmyadmin-secure.tls=true
    depends_on:
      - db
    links:
      - db
    networks:
      - web
      - default

  # USAGE: docker-compose run --rm wpcli plugin list
  wpcli:
    image: wordpress:cli-php7.4
    depends_on:
      - db
      - wp
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: "local_wp_${PROJECT_NAME}"
    volumes:
      - ./wp-core:/var/www/html
      - ./${THEME_NAME}:/var/www/html/wp-content/themes/${THEME_NAME}
      - ./${THEME_NAME}-child:/var/www/html/wp-content/themes/${THEME_NAME}-child
      - ./uploads:/var/www/html/wp-content/uploads
      - ./plugins:/var/www/html/wp-content/plugins
    links:
        - db
    networks:
      - default

  smtp:
    image: mailhog/mailhog:latest
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=local_traefik_webgateway
      - traefik.http.services.${PROJECT_NAME}-mailhog.loadbalancer.server.port=8025
      - traefik.http.routers.${PROJECT_NAME}-mailhog.rule=Host(`mailhog.${URL}`)
      - traefik.http.routers.${PROJECT_NAME}-mailhog.entrypoints=web
    networks:
      - web
      - default


networks:
  web:
    external:
      name: local_traefik_webgateway
  default:
    driver: bridge
