version: '3.1'

services:
  wp:
    image: noveni/wordpress:5.5-php7.3-apache-dev
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: local_db_user
      WORDPRESS_DB_PASSWORD: noveni
      WORDPRESS_DB_NAME: "local_wp_${PROJECT_NAME}"
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
    volumes:
      - ./wp-core:/var/www/html
      - ./${THEME_NAME}:/var/www/html/wp-content/themes/${THEME_NAME}
      - ./wp/wp-content/uploads:/var/www/html/wp-content/uploads
      - ./wp/wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp/wp-content/languages:/var/www/html/wp-content/languages
    labels:
      - traefik.enable=true
      - traefik.docker.network=local_traefik_webgateway
      - traefik.http.routers.${PROJECT_NAME}.rule=Host(`${URL}`)
      - traefik.http.routers.${PROJECT_NAME}.entrypoints=web
      - traefik.http.routers.${PROJECT_NAME}-secure.rule=Host(`${URL}`)
      - traefik.http.routers.${PROJECT_NAME}-secure.entrypoints=websecure
      - traefik.http.routers.${PROJECT_NAME}-secure.tls=true
    networks:
      - web
      - default

  db:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_DATABASE: "local_wp_${PROJECT_NAME}"
      MYSQL_USER: local_db_user
      MYSQL_PASSWORD: noveni
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./.db:/var/lib/mysql
    networks:
      - default

  phpmyadmin:
    image: noveni/phpmyadmin
    restart: always
    environment:
      MYSQL_USER: "local_db_user"
      MYSQL_PASSWORD: "noveni"
    labels:
      - traefik.enable=true
      - traefik.docker.network=local_traefik_webgateway
      - traefik.http.routers.${PROJECT_NAME}-phpmyadmin-secure.rule=Host(`phpmyadmin.${URL}`)
      - traefik.http.routers.${PROJECT_NAME}-phpmyadmin-secure.entrypoints=websecure
      - traefik.http.routers.${PROJECT_NAME}-phpmyadmin-secure.tls=true
    depends_on:
      - db
    links:
      - db
    networks:
      - web
      - default

  # USAGE: docker-compose run --rm wpcli plugin list
  wpcli:
    image: noveni/wordpress:cli-php7.3
    depends_on:
      - db
      - wp
    volumes:
      - ./wp-core:/var/www/html
      - ./${THEME_NAME}:/var/www/html/wp-content/themes/${THEME_NAME}
      - ./wp/wp-content/uploads:/var/www/html/wp-content/uploads
      - ./wp/wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp/wp-content/languages:/var/www/html/wp-content/languages
    networks:
      - default

  smtp:
    image: mailhog/mailhog:latest
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=local_traefik_webgateway
      - traefik.http.services.${PROJECT_NAME}-mailhog.loadbalancer.server.port=8025
      - traefik.http.routers.${PROJECT_NAME}-mailhog.rule=Host(`mailhog.${URL}`)
      - traefik.http.routers.${PROJECT_NAME}-mailhog.entrypoints=web
    networks:
      - web
      - default


networks:
  web:
    external:
      name: local_traefik_webgateway
  default:
    driver: bridge
